# https://crates.io/crates/mdbook

[book]
authors = ["convexbrain"]
language = "ja"
multilingual = false
src = "src"
title = "TotsuBook 日本語"

[output.html]
mathjax-support = true
google-analytics = "UA-57046411-1"
