remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

locale: "ja-JP"

title: "convexbrainのけんきうメモ"
title_separator: "|"
name: "convexbrain"

url: "https://convexbrain.github.io/studynotes/"
repository: "convexbrain/studynotes"

head_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML

search: true

twitter:
  username: "convexbrain"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-57046411-1"
    anonymize_ip: false # default

author:
  name   : "convexbrain"
  avatar : #"/assets/images/bio-photo.jpg"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
